{{- if .Values.configMap.configServer.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  application.properties: |
    server.port=8888
    spring.cloud.config.server.git.uri=https://github.com/ThuanPhuc27/spring-petclinic-microservices-config
    spring.cloud.config.server.git.default-label=main
{{- end }}
