{{- if .Values.configMap.discoveryServer.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  application.properties: |
    spring.application.name=discovery-server
    spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://petclinic-config-server-service:8888/}
    management.endpoints.web.exposure.include="*"
    management.endpoint.health.show-details=always
    management.tracing.enabled=true
    management.tracing.sampling.probability=1.0
    management.zipkin.tracing.enabled=true
    management.zipkin.tracing.endpoint=http://tracing-server-service.default.svc.cluster.local:9411/api/v2/spans
    management.metrics.distribution.percentiles-histogram.http.server.requests=true
    management.metrics.enable.exemplars=true
    logging.pattern.console=%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) level="%p" time="%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}" service="${spring.application.name}" traceId="%X{traceId:-}" spanId="%X{spanId:-}" thread="%t" logger="%logger{39}" message="%m"%n
    logging.pattern.file=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} level="%p" time="%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}" service="${spring.application.name}" traceId="%X{traceId:-}" spanId="%X{spanId:-}" thread="%t" logger="%logger{39}" message="%m"%n
    
    # Logging levels
    logging.level.io.micrometer.tracing=${LOGGING_LEVEL_IO_MICROMETER_TRACING:DEBUG}
    logging.level.org.springframework.cloud.sleuth=DEBUG
    logging.level.org.springframework.cloud.sleuth.autoconfig=DEBUG
    logging.level.org.springframework.web=DEBUG
    
    # Charset
    logging.charset.console=UTF-8
    logging.charset.file=UTF-8
{{- end }}