######### Deployment ########
deployment:
  create: true

appName: petclinic-genai-service
namespace: petclinic-dev

#spec
replicaCount: 1
revisionHistoryLimit: 11

rollingUpdate:
  maxSurge: "25%"
  maxUnavailable: "25%"

pullFromPrivateRegistry:
  enabled: true
  secretName: "dockerhub"

initContainers:
  - name: wait-for-config-server
    image: darthcabs/tiny-tools:1
    command:
      ["sh", "-c", "until curl -s http://petclinic-config-server-service:8888/; do echo waiting for config server; sleep 5; done"]

  - name: wait-for-discovery-server
    image: darthcabs/tiny-tools:1
    command:
      ["sh", "-c", "until curl -s http://petclinic-discovery-server-service:8761/; do echo waiting for discovery server; sleep 5; done"]

appImage: "thuanlp/spring-petclinic-genai-service"
appVersion: "latest"
containerPort: 8084

volumes:
  - configMap:
      defaultMode: 420
      name: "petclinic-genai-service-application-properties-configmap"
    name: "petclinic-genai-service-application-properties-config-volume"

volumeMounts:
  - name: "petclinic-genai-service-application-properties-config-volume"
    mountPath: /app/config/application.properties
    subPath: application.properties

######### Service ########
service:
  create: true
  type: NodePort
  port: 8084
  targetPort: 8084
  nodePort: 30084

######### ConfigMap ########
configmap:
  genai-service:
    create: true