appName: petclinic-config-server
env: staging
image:
  repository: runandgo/spring-petclinic-config-server
  tag: v1.2.11
  pullSecret: dockerhub
  pullPolicy: Always
service:
  port: 8888
  type: ClusterIP

configMap:
  configServer:
    create: true
  name: petclinic-config-server-application-properties-configmap

ingress:
  domainName: config-server.lptdevops.website
  path: /
  pathType: Prefix