appName: petclinic-config-server
env: dev
image:
  repository: thuanlp/spring-petclinic-config-server
  tag: latest
  pullSecret: dockerhub
  pullPolicy: Always
service:
  port: 8888
  type: ClusterIP

configMap:
  configServer:
    create: true
  name: petclinic-config-server-application-properties-configmap

ingress:
  tls:
    - hosts:
        - config-server-dev.lptdevops.website
      secretName: config-tls
  domainName: config-server-dev.lptdevops.website
  path: /
  pathType: Prefix
