appName: petclinic-discovery-server
env: dev
image:
  repository: runandgo/spring-petclinic-discovery-server
  tag: dev
  pullSecret: dockerhub
  pullPolicy: Always
service:
  port: 8761
  type: ClusterIP
initContainers:
  - name: init-discovery-server
    image: darthcabs/tiny-tools:1
    command: ["sh", "-c", "until curl -s http://petclinic-config-server-service:8888/; do echo waiting for config server; sleep 5; done"]
configMap:
  discoveryServer:
    create: true
  name: petclinic-discovery-server-application-properties-configmap

ingress:
  domainName: discovery-server-dev.lptdevops.website
  path: /
  pathType: Prefix
global:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"