{{- if .Values.configMap.genaiService.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  application.properties: |
    spring.main.web-application-type=reactive
    spring.application.name=genai-service
    spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://petclinic-config-server-service:8888/},optional:classpath:/creds.yaml
    spring.ai.chat.client.enabled=true
    spring.ai.azure.openai.api-key="kh"
    spring.ai.azure.openai.endpoint="kh"
    spring.ai.azure.openai.chat.options.temperature=0.7
    spring.ai.azure.openai.chat.deployment-name=gpt-4o
    spring.ai.openai.api-key="kj"
    spring.ai.openai.chat.options.temperature=0.7
    spring.ai.openai.chat.options.model=gpt-4o-mini
    logging.level.org.springframework.ai.chat.client.advisor=DEBUG
{{- end }}