{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-service"
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: tcp
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
{{- end }}
