{{- if .Values.tracing-server.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-server
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-server
  template:
    metadata:
      labels:
        app: tracing-server
    spec:
      containers:
        - name: tracing-server
          image: openzipkin/zipkin
          resources:
            limits:
              memory: 512Mi
          ports:
            - containerPort: 9411

---

apiVersion: v1
kind: Service
metadata:
  name: tracing-server
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: tracing-server
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
  type: ClusterIP 
{{- end }}
