apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: petclinic-staging
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: admin-server
            path: charts/admin-server
          - name: api-gateway
            path: charts/api-gateway
          - name: config-server
            path: charts/config-server
          - name: customers-service
            path: charts/customers-service
          - name: visits-service
            path: charts/visits-service
          - name: discovery-server
            path: charts/discovery-server
          - name: genai-service
            path: charts/genai-service
          - name: vets-service
            path: charts/vets-service
  template:
    metadata:
      name: '{{name}}-staging'
      namespace: argocd
    spec:
      project: petclinic-staging
      source:
        repoURL: https://github.com/ThuanPhuc27/Petclinic_HelmChart
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - staging-values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: petclinic-staging
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true