appName: petclinic-admin-server
namespace: petclinic-dev
image:
  repository: thuanlp/spring-petclinic-admin-server
  tag: latest
  pullSecret: dockerhub
  pullPolicy: Always
service:
  port: 9090
  type: NodePort
  nodePort: 30090
initContainers:
  - name: wait-for-config-server
    image: darthcabs/tiny-tools:1
    command: ["sh", "-c", "until curl -s http://petclinic-config-server-service:8888/; do echo waiting for config server; sleep 5; done"]
  - name: wait-for-discovery-server
    image: darthcabs/tiny-tools:1
    command: ["sh", "-c", "until curl -s http://petclinic-discovery-server-service:8761/; do echo waiting for discovery server; sleep 5; done"]
configMap:
  admin-server:
    create: true
  name: petclinic-admin-server-application-properties-configmap
