apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-server-dev
  namespace: argocd   # namespace ArgoCD đang chạy, thường là argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: config-server=thuanlp/spring-petclinic-config-server:latest
    argocd-image-updater.argoproj.io/config-server.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/config-server.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/config-server.update-strategy: digest
    argocd-image-updater.argoproj.io/config-server.allow-tags: latest
    argocd-image-updater.argoproj.io/config-server.pull-secret: pullsecret:argocd/dockerhub
spec:
  project: petclinic-dev
  source:
    repoURL: https://github.com/ThuanPhuc27/Petclinic_HelmChart
    path: charts/config-server
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace:  petclinic-dev   # namespace để deploy app config-server
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
